Traceback (most recent call last):
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ka50\miniconda3\envs\IN-CORE_GAlveston\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pyincore import IncoreClient

# Request user to input their IN-CORE credentials
username = input("Please enter your IN-CORE username: ")
password = input("Please enter your IN-CORE password: ")

# Test the credentials
client = IncoreClient()

# Print a success message if credentials are correct
print("Successfully connected to IN-CORE!")

# Note: Ensure to handle any exceptions or errors related to incorrect credentials in the actual implementation.

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyincore[39;00m [38;5;28;01mimport[39;00m IncoreClient
[0;32m      3[0m [38;5;66;03m# Request user to input their IN-CORE credentials[39;00m
[0;32m      4[0m username [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mPlease enter your IN-CORE username: [39m[38;5;124m"[39m)

[1;31mModuleNotFoundError[0m: No module named 'pyincore'

